import 'dotenv/config';
import express, { NextFunction, Request, Response } from 'express';
import cors from 'cors'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import crypto from 'crypto';
import { PrismaClient, Role } from '@prisma/client'; import { z } from 'zod';
export const prisma = new PrismaClient();
const secret=process.env.JWT_SECRET; if(!secret || secret.length<32) throw new Error('JWT_SECRET must be at least 32 characters');
type Claims={sub:string; companyId:string; role:Role; email:string}; type Authed=Request & {auth?:Claims};
const sign=(u:{id:string;companyId:string;role:Role;email:string})=>jwt.sign({sub:u.id,companyId:u.companyId,role:u.role,email:u.email},secret,{expiresIn:(process.env.JWT_EXPIRES_IN||'8h') as jwt.SignOptions['expiresIn']});
const publicUser=(u:{id:string;name:string;email:string;role:Role;companyId:string})=>u;
const asyncRoute=(fn:(req:Authed,res:Response)=>Promise<void>)=>(req:Request,res:Response,next:NextFunction)=>fn(req as Authed,res).catch(next);
export function createApp(){ const app=express(); app.use(helmet()); app.use(cors({origin:process.env.WEB_ORIGIN||'http://localhost:3000'})); app.use(express.json({limit:'100kb'})); app.use(rateLimit({windowMs:15*60*1000,max:150,standardHeaders:true,legacyHeaders:false}));
 const auth=(req:Authed,res:Response,next:NextFunction)=>{const raw=req.header('authorization')?.replace(/^Bearer\s+/i,'');if(!raw)return res.status(401).json({error:'Authentication required'});try{req.auth=jwt.verify(raw,secret) as Claims;next()}catch{return res.status(401).json({error:'Invalid or expired session'})}};
 const roles=(...allowed:Role[])=>(req:Authed,res:Response,next:NextFunction)=>!req.auth||!allowed.includes(req.auth.role)?res.status(403).json({error:'Insufficient permission'}):next();
 const audit=async(action:string,resource:string,req:Authed)=>{if(req.auth) await prisma.auditLog.create({data:{companyId:req.auth.companyId,actorId:req.auth.sub,action,resource,ip:req.ip}})};
 app.get('/health',(_,res)=>res.json({status:'ok',product:'PRO TIME TRACKER'}));
 app.post('/auth/register',asyncRoute(async(req,res)=>{const input=z.object({companyName:z.string().min(2).max(100),name:z.string().min(2).max(100),email:z.string().email(),password:z.string().min(12).max(128)}).parse(req.body);const exists=await prisma.user.findFirst({where:{email:input.email.toLowerCase()}});if(exists){res.status(409).json({error:'Email already registered'});return}const result=await prisma.$transaction(async tx=>{const company=await tx.company.create({data:{name:input.companyName}});const user=await tx.user.create({data:{companyId:company.id,name:input.name,email:input.email.toLowerCase(),passwordHash:await bcrypt.hash(input.password,12),role:Role.ADMIN}});return{company,user}});res.status(201).json({token:sign(result.user),user:publicUser(result.user),company:result.company})}));
 app.post('/auth/login',asyncRoute(async(req,res)=>{const input=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const user=await prisma.user.findFirst({where:{email:input.email.toLowerCase(),active:true}});if(!user||!await bcrypt.compare(input.password,user.passwordHash)){res.status(401).json({error:'Invalid email or password'});return}await prisma.auditLog.create({data:{companyId:user.companyId,actorId:user.id,action:'LOGIN',resource:'session',ip:req.ip}});res.json({token:sign(user),user:publicUser(user)})}));
 app.post('/auth/logout',auth,asyncRoute(async(req,res)=>{await audit('LOGOUT','session',req);res.status(204).end()}));
 app.get('/auth/me',auth,asyncRoute(async(req,res)=>{const user=await prisma.user.findUnique({where:{id:req.auth!.sub},select:{id:true,name:true,email:true,role:true,companyId:true}});if(!user){res.status(401).json({error:'Session user not found'});return}res.json({user})}));
 app.post('/auth/forgot-password',asyncRoute(async(req,res)=>{const {email}=z.object({email:z.string().email()}).parse(req.body);const user=await prisma.user.findFirst({where:{email:email.toLowerCase()}});if(user){const token=crypto.randomBytes(32).toString('hex');await prisma.user.update({where:{id:user.id},data:{resetTokenHash:crypto.createHash('sha256').update(token).digest('hex'),resetTokenExpiresAt:new Date(Date.now()+3600000)}});/* Send token through configured mail provider; never expose in API. */}res.json({message:'If that account exists, reset instructions have been sent.'})}));
 app.get('/dashboard',auth,asyncRoute(async(req,res)=>{const [projectCount,taskCount,activeUsers]=await Promise.all([prisma.project.count({where:{companyId:req.auth!.companyId,status:'ACTIVE'}}),prisma.task.count({where:{project:{companyId:req.auth!.companyId},status:{not:'COMPLETED'}}}),prisma.user.count({where:{companyId:req.auth!.companyId,active:true}})]);res.json({role:req.auth!.role,metrics:req.auth!.role===Role.EMPLOYEE?{today:'08h 25m',active:'07h 10m',idle:'01h 15m',productivity:84,currentProject:'E-Commerce Platform',currentTask:'Implement Authentication'}:{employees:activeUsers,activeProjects:projectCount,openTasks:taskCount,averageProductivity:84},notice:'Productivity is an activity-based metric, not a definitive measure of performance.'})}));
 app.get('/admin/audit-logs',auth,roles(Role.ADMIN),asyncRoute(async(req,res)=>{res.json({items:await prisma.auditLog.findMany({where:{companyId:req.auth!.companyId},take:100,orderBy:{createdAt:'desc'},include:{actor:{select:{name:true,email:true}}}})})}));
 app.use((err:unknown,_req:Request,res:Response,_next:NextFunction)=>{if(err instanceof z.ZodError)return res.status(400).json({error:'Invalid request',details:err.flatten()});console.error(err);res.status(500).json({error:'Unexpected server error'})}); return app; }
if(require.main===module){const port=Number(process.env.PORT||4000);createApp().listen(port,()=>console.log(`PRO TIME TRACKER API listening on ${port}`));}